General:
  seed: 3927

Data:
  dataset: DATASET_NAME
  num_genes: NUM_GENES
  folds: 8
  path: PATH_TO_DATASET
  slides: PATH_TO_SLIDES

CNN:
  pretrained_path: 'pretrained/model-low-v1.pth'
  batch_size: 8
  epochs: 15
  dropout: 0.2
  optimizer:
    type: adam
    lr: 0.00005
    weight_decay: 0.0
  scheduler:
    type: step
    step_size: 2
    gamma: 0.5


GNN:
  type: GAT
  epochs: 400
  attn_heads: 8
  drop_edge: 0.2
  optimizer:
    type: adam
    lr: 0.001
    weight_decay: 0.0
  scheduler:
    type: warmup
    warmup_steps: 10
